import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
// import Sockets from '../components/sockets'
import styles from '../styles/Home.module.css';
import Layout from '../components/Layout';
import Map from '../components/Map';
import Carousel from '../components/Carousel';

const Home: NextPage = () => {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/public/icons8-ski-96.png" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>Find you next ski instructor here!</h1>
          <p className={styles.description}>
            Click on the map below to find an instructor in your
          </p>
          <Map />
          <p className={styles.description}>
          Search resorts in your area below:
          </p>
          <Carousel />
        </main>

      </div>
    </Layout>
  );
};

export default Home;
