import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
// import Sockets from '../components/sockets'
import styles from '../styles/Home.module.css'
import Nav from '../components/Nav'
import Map from '../components/Map'
import Carousel from '../components/Carousel'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Nav/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/icons8-ski-96.png" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Find you next ski instructor here!
        </h1>
        <p className={styles.description}>
          Click on the map below to find an instructor in your
        </p>
        <Map/>
        {/* <p className={styles.description}>
          Search resorts in your area below:
          </p> */}
        <Carousel/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
